version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/djapp

hooks:
  BeforeInstall:
    - location: deployment_script/install_requirements.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deployment_script/start_server.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: deployment_script/stop_server.sh
      timeout: 300
      runas: root
